### ISSUE TITLE
Request for the UT2BuildToolkit

### ISSUE THREAD

**Issue by NOOTLORD** [aldehir/ut2004-patches#3]
Hi aldehir, (Yes i know issues are not supposed to be used for this but this seemed like my only hope)

First off all great work on the project! the changes look promising and i am eager to see where u will go next with the project!
I stumbled on the project today and would like to get your fixes compiled into a build so i can poke around with it myself, but i noticed this part in the build guide: **I have compiled all the necessary tools, headers, and libraries necessary to build UT2 into a single archive. Feel free to reach out if you'd like a copy**. Whilst i do have the source lying around somewhere i don't want to setup vs 2003 if i can avoid it.

I would like to request a copy of the UT2BuildToolkit but i was unable to find any contact information, how would i go about contacting u? Hope to hear from u soon 😄 

Kind regards
Reinder

**Comment by aldehir** [comment]
@NOOTLORD, Absolutely no problem. You can reach me on discord, my user id is `kokuei`. I'll happily supply the toolkit.
