### ISSUE TITLE
UT2004 freezes when in windowd mode

### ISSUE THREAD

**Issue by NOOTLORD** [aldehir/ut2004-patches#4]
**Bug:** game freezes when u have the game in windowed mode but the window is not selected/in focus. All sounds still play in the background suggesting that the engine itself is still doing its game loop correctly but it seems the DX8 renderer just dies. 

(**Edit** it seems to be the renderer because when i use a wrapper like dgVoodoo it fixes this issue, both dx9 and 11/12 work correctly)

**Release used:** v3369.1-alpha-7

**How to reproduce:** Start UT2004 in windowed mode and then click away from the window to deselect/unfocus it, wait 5/6 seconds and watch the game freeze (works in both the main menu and in any offline/online match)

If u require more info feel free to reach out, sadly no errors where generated

**Comment by aldehir** [comment]
The freezing comes from mouse input messages not being processed. For some reason the input tick is hindered when out of focus for a few people. Knowing the renderer might be the culprit will help in further diagnosing this issue, so thank you for that information. I'll see what I can find out.

**Comment by NOOTLORD** [comment]
Hmm alright, ye i was just curious if a different renderer would fix it and well it did :P 
If u require more testing after u made some changes to it feel free to reach out 😄
