### ISSUE TITLE
Dedicated server crashes after it finishes loading

### ISSUE THREAD

**Issue by NOOTLORD** [aldehir/ut2004-patches#7]
**Bug:** the dedicated server will crash once its get past it startup phase and is ready to receive connections, this issue does not happen when using a listen aka peer to peer server. (Turning the LAN server option on or off made no change either)

**Release used:** v3369.1-alpha-8 

**How to reproduce:** Start UT2004 hit host game and choose the dedicated option, it will appear to load fine at first but once it gets to the following line: Log: Startup time: x.xx seconds the server crashes with the following log entry's:

Critical: EnforceTickRate
Critical: MainLoop
Critical: FMallocWindows::Free
Critical: FMallocWindows::Realloc
Critical: 1090F561 0 FArray
Critical: FArray::Realloc
Critical: 0*2
Critical: FMallocWindows::Free
Exit: Executing UObject::StaticShutdownAfterError
Exit: Exiting.

(Attached the log file as well, with or without mods the same crash behavior happens)

[server.log](https://github.com/aldehir/ut2004-patches/files/12919602/server.log)

**Comment by aldehir** [comment]
I will need to package `UCC.exe` to support the dedicated server.
